#yaya
#--------------------------------------

# Header
menu:
  HOME: /
  ABOUT: /about
  RSS: /atom.xml

# Sidebar
widgets:
- Categories
- Tags
- Archives
- Tagcloud
- Recent_Posts

# Content
excerpt_link: 阅读全文

# 其他
favicon: /favicon.ico